/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
  java
}

sourceSets {
  main {
    java {
      srcDir("src/maytree")
    }
  }

  test {
    java {
      srcDir("test/maytree")
    }
  }
}

repositories {
  jcenter()
}

dependencies {
  implementation("org.hibernate:hibernate-entitymanager:5.4.10.Final")
  testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.2")
  testImplementation("com.google.truth:truth:1.0")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.5.2")
}

tasks.test {
  useJUnitPlatform()
}
